# Generated by Django 2.1.7 on 2019-04-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articles_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章汇总',
                'verbose_name_plural': '文章汇总',
                'db_table': 'articles',
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='ForumBlock',
            fields=[
                ('block_ID', models.AutoField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': '论坛版块',
                'verbose_name_plural': '论坛板块',
                'db_table': 'forum_block',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_article', to='forum.ForumBlock'),
        ),
    ]
