# Generated by Django 2.1.7 on 2019-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='praise_points',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
